"""posts table

Revision ID: 844aac653641
Revises: 3bfbfeef5478
Create Date: 2021-05-10 15:35:19.723591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844aac653641'
down_revision = '3bfbfeef5478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Mark', sa.Integer(), nullable=True),
    sa.Column('Finish_Time', sa.DateTime(), nullable=True),
    sa.Column('Feedback', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_Finish_Time'), 'post', ['Finish_Time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_Finish_Time'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
